---
config:
  look: neo
---
flowchart LR
 subgraph Scan_Layer["Scan_Layer"]
        ZMapWrapper["Wrapper → Kafka"]
        ZMap["Descoberta de hosts"]
        MasscanWrapper["Wrapper → Kafka"]
        Masscan["Enum portas"]
        BGrabWrapper["Wrapper → Kafka"]
        BGrab["Fingerprint"]
  end
 subgraph Kafka_Layer["Kafka_Layer"]
        KafkaHosts[("Kafka: hosts.discovered")]
        KafkaEndpoints[("Kafka: endpoints.discovered")]
        KafkaServices[("Kafka: services.observed")]
  end
 subgraph Elastic_Layer["Elastic_Layer"]
        ElasticHosts["Elastic\nhosts index"]
        ElasticEndpoints["Elastic\nendpoints index"]
        ElasticServices["Elastic\nservices index"]
  end
    ZMap --> ZMapWrapper
    Masscan --> MasscanWrapper
    BGrab --> BGrabWrapper
    ZMapWrapper --> KafkaHosts
    KafkaHosts --> MasscanWrapper & ElasticHosts
    MasscanWrapper --> KafkaEndpoints
    KafkaEndpoints --> BGrabWrapper & ElasticEndpoints
    BGrabWrapper --> KafkaServices
    KafkaServices --> ElasticServices
